import type { InvoiceDictionary } from "./dictionary";

// БУМАГА ИНВОЙСА НА ОСТАЛЬНЫХ ЯЗЫКАХ ПРИЛОЖЕНИЯ (владелец 2026-10-04: «выбор
// языка в инвойсе… я могу выбирать язык соответственно тому, что я выберу»).
// Русский и английский живут в `dictionary.ts`; здесь — болгарский, греческий,
// украинский, немецкий и испанский, тем же набором полей.
//
// VAT — СЛОВО ВЛАДЕЛЬЦА НА ЛЮБОМ ЯЗЫКЕ (как и на русской бумаге): один
// документ говорит про один налог одним словом.
// Файл в `packages/shared/src/i18n/ignore.json`: язык бумаги выбирают на
// документе, перевод интерфейса его не трогает.

export const BG: InvoiceDictionary = {
  locale: "bg-BG",
  invoice: "ФАКТУРА",
  draft: "Чернова",
  seller: "Доставчик",
  recipient: "Получател",
  sellerMissing: "Доставчикът не е посочен",
  recipientMissing: "Получателят не е посочен",
  issuedOn: "Дата на издаване",
  dueOn: "Срок за плащане",
  notSet: "Не е посочена",
  lineTitle: "Описание",
  qty: "К-во",
  price: "Цена",
  amount: "Сума",
  untitled: "Без наименование",
  subtotal: "Сума",
  vatInclusive: "вкл. VAT",
  vatExclusive: "VAT",
  netAmount: "Сума без VAT",
  discount: "Отстъпка",
  vatOn: (amount) => `върху ${amount}`,
  vatOf: (percent) => `VAT · ${percent}`,
  grandTotal: "За плащане",
  regNumber: "Рег. №",
  vatNo: "VAT №",
  addrEntrance: (value) => `вх. ${value}`,
  addrFloor: (value) => `ет. ${value}`,
  addrApartment: (value) => `ап. ${value}`,
  // «Дата:», а не «Издадена»: строка печатается и под «кредитно известие»
  // (средний род).
  issuedShort: (date) => `Дата: ${date}`,
  dueShort: (date) => `Платима до ${date}`,
  notesTitle: "Забележка",
  numberPending: "Номерът се присвоява при издаване",
  paymentPurpose: (number) => `В основанието за плащане посочете номер ${number}.`,
  method_cash: "В брой",
  method_card: "Карта",
  method_bank: "Банков превод",
  method_other: "Друго",
  footer: (number) => `Фактура ${number}`,
  payTo: "Данни за плащане",
  bank: "Банка",
  payment: "Плащане",
  status: "Статус",
  paid: "Платено",
  remaining: "Остатък",
  paymentRow: "Плащане",
  refundRow: "Възстановяване",
  notes: "Бележки",
  invoiceEyebrow: "Фактура",
  creditNote: "КРЕДИТНО ИЗВЕСТИЕ",
  creditNoteEyebrow: "Кредитно известие",
  creditNoteFor: (number) => `Към фактура ${number}`,
  // Кредитное известие сторнирует фактуру; «анулиране» — это отмена ошибочной.
  creditNoteLine: (number) => (number ? `Сторниране на фактура ${number}` : "Сторниране на фактура"),
  creditNoteFooter: (number) => `Кредитно известие ${number}`,
  creditNoteTotal: "Общо",
  creditNoteForReceipt: (number) => `Към разписка ${number}`,
  creditNoteReceiptLine: (number) => (number ? `Възстановяване по разписка ${number}` : "Възстановяване по разписка"),
  creditNotePartialLine: (number) =>
    number ? `Частично сторниране на фактура ${number}` : "Частично сторниране на фактура",
  paymentsDate: "Дата",
  paymentsOperation: "Операция",
  paymentsEmpty: "Все още няма потвърдени плащания.",
  linesTableLabel: "Позиции на фактурата",
  paymentsTableLabel: "История на плащанията",
  linesEmpty: "Все още няма позиции.",
  status_issued: "Издадена",
  status_partial: "Частично платена",
  status_overdue: "Просрочена",
  status_paid: "Платена",
  status_void: "Анулирана",
  status_cancelled: "Сторнирана",
};

export const EL: InvoiceDictionary = {
  locale: "el-GR",
  invoice: "ΤΙΜΟΛΟΓΙΟ",
  draft: "Πρόχειρο",
  seller: "Εκδότης",
  // «Παραλήπτης» — получатель груза; сторона счёта — «Πελάτης».
  recipient: "Πελάτης",
  sellerMissing: "Δεν έχει οριστεί εκδότης",
  recipientMissing: "Δεν έχει οριστεί πελάτης",
  issuedOn: "Ημερομηνία έκδοσης",
  dueOn: "Προθεσμία πληρωμής",
  notSet: "Δεν ορίστηκε",
  lineTitle: "Περιγραφή",
  qty: "Ποσ.",
  price: "Τιμή",
  // «Αξία», а не «Ποσό»: рядом стоит «Ποσ.» (количество).
  amount: "Αξία",
  untitled: "Χωρίς τίτλο",
  subtotal: "Υποσύνολο",
  vatInclusive: "συμπ. VAT",
  vatExclusive: "VAT",
  netAmount: "Ποσό χωρίς VAT",
  discount: "Έκπτωση",
  vatOn: (amount) => `επί ${amount}`,
  vatOf: (percent) => `VAT · ${percent}`,
  grandTotal: "Πληρωτέο",
  regNumber: "Αρ. Εγγραφής",
  vatNo: "Αρ. VAT",
  addrEntrance: (value) => `Είσοδος ${value}`,
  addrFloor: (value) => `Όροφος ${value}`,
  addrApartment: (value) => `Διαμ. ${value}`,
  issuedShort: (date) => `Έκδοση ${date}`,
  dueShort: (date) => `Πληρωτέο έως ${date}`,
  notesTitle: "Σημείωση",
  numberPending: "Ο αριθμός θα αποδοθεί κατά την έκδοση",
  paymentPurpose: (number) => `Αναφέρετε τον αριθμό ${number} στην αιτιολογία της πληρωμής.`,
  method_cash: "Μετρητά",
  method_card: "Κάρτα",
  method_bank: "Τραπεζική μεταφορά",
  method_other: "Άλλο",
  footer: (number) => `Τιμολόγιο ${number}`,
  payTo: "Στοιχεία πληρωμής",
  bank: "Τράπεζα",
  payment: "Πληρωμή",
  status: "Κατάσταση",
  paid: "Πληρωμένο",
  remaining: "Υπόλοιπο",
  paymentRow: "Πληρωμή",
  refundRow: "Επιστροφή",
  notes: "Σημειώσεις",
  invoiceEyebrow: "Τιμολόγιο",
  creditNote: "ΠΙΣΤΩΤΙΚΟ ΤΙΜΟΛΟΓΙΟ",
  creditNoteEyebrow: "Πιστωτικό τιμολόγιο",
  creditNoteFor: (number) => `Αφορά το τιμολόγιο ${number}`,
  creditNoteLine: (number) => (number ? `Ακύρωση τιμολογίου ${number}` : "Ακύρωση τιμολογίου"),
  creditNoteFooter: (number) => `Πιστωτικό τιμολόγιο ${number}`,
  creditNoteTotal: "Σύνολο",
  creditNoteForReceipt: (number) => `Αφορά την απόδειξη ${number}`,
  creditNoteReceiptLine: (number) => (number ? `Επιστροφή για την απόδειξη ${number}` : "Επιστροφή για την απόδειξη"),
  creditNotePartialLine: (number) =>
    number ? `Μερική ακύρωση τιμολογίου ${number}` : "Μερική ακύρωση τιμολογίου",
  paymentsDate: "Ημερομηνία",
  paymentsOperation: "Συναλλαγή",
  paymentsEmpty: "Δεν υπάρχουν ακόμη επιβεβαιωμένες πληρωμές.",
  linesTableLabel: "Γραμμές τιμολογίου",
  paymentsTableLabel: "Ιστορικό πληρωμών",
  linesEmpty: "Δεν υπάρχουν ακόμη γραμμές.",
  status_issued: "Εκδόθηκε",
  status_partial: "Μερικώς πληρωμένο",
  status_overdue: "Ληξιπρόθεσμο",
  status_paid: "Εξοφλημένο",
  status_void: "Ακυρωμένο",
  status_cancelled: "Αντιλογισμένο",
};

export const UK: InvoiceDictionary = {
  locale: "uk-UA",
  invoice: "ІНВОЙС",
  draft: "Чернетка",
  seller: "Продавець",
  recipient: "Отримувач",
  sellerMissing: "Продавця не вказано",
  recipientMissing: "Отримувача не вказано",
  issuedOn: "Дата виставлення",
  dueOn: "Сплатити до",
  notSet: "Не вказано",
  lineTitle: "Назва",
  qty: "К-сть",
  price: "Ціна",
  amount: "Сума",
  untitled: "Без назви",
  subtotal: "Сума",
  vatInclusive: "у т.ч. VAT",
  vatExclusive: "VAT",
  netAmount: "Сума без VAT",
  discount: "Знижка",
  vatOn: (amount) => `з ${amount}`,
  vatOf: (percent) => `VAT · ${percent}`,
  grandTotal: "До сплати",
  regNumber: "Реєстр. №",
  vatNo: "VAT №",
  addrEntrance: (value) => `під’їзд ${value}`,
  addrFloor: (value) => `пов. ${value}`,
  addrApartment: (value) => `кв. ${value}`,
  issuedShort: (date) => `Виставлено ${date}`,
  dueShort: (date) => `Сплатити до ${date}`,
  notesTitle: "Примітка",
  numberPending: "Номер буде присвоєно під час виставлення",
  paymentPurpose: (number) => `У призначенні платежу вкажіть номер ${number}.`,
  method_cash: "Готівка",
  method_card: "Картка",
  method_bank: "Переказ",
  method_other: "Інше",
  footer: (number) => `Інвойс ${number}`,
  payTo: "Реквізити для оплати",
  bank: "Банк",
  payment: "Оплата",
  status: "Статус",
  paid: "Сплачено",
  remaining: "Залишок",
  paymentRow: "Платіж",
  refundRow: "Повернення",
  notes: "Коментар",
  invoiceEyebrow: "Інвойс",
  creditNote: "КРЕДИТ-НОТА",
  creditNoteEyebrow: "Кредит-нота",
  creditNoteFor: (number) => `До інвойсу ${number}`,
  creditNoteLine: (number) => (number ? `Скасування інвойсу ${number}` : "Скасування інвойсу"),
  creditNoteFooter: (number) => `Кредит-нота ${number}`,
  creditNoteTotal: "Разом",
  creditNoteForReceipt: (number) => `До квитанції ${number}`,
  creditNoteReceiptLine: (number) => (number ? `Повернення за квитанцією ${number}` : "Повернення за квитанцією"),
  creditNotePartialLine: (number) =>
    number ? `Часткове скасування інвойсу ${number}` : "Часткове скасування інвойсу",
  paymentsDate: "Дата",
  paymentsOperation: "Операція",
  paymentsEmpty: "Підтверджених оплат поки немає.",
  linesTableLabel: "Позиції інвойсу",
  paymentsTableLabel: "Історія платежів",
  linesEmpty: "Позиції ще не заповнено.",
  status_issued: "Виставлено",
  status_partial: "Частково сплачено",
  status_overdue: "Прострочено",
  status_paid: "Сплачено",
  status_void: "Анульовано",
  status_cancelled: "Скасовано",
};

export const DE: InvoiceDictionary = {
  locale: "de-DE",
  invoice: "RECHNUNG",
  draft: "Entwurf",
  seller: "Von",
  recipient: "Rechnung an",
  sellerMissing: "Rechnungssteller fehlt",
  recipientMissing: "Empfänger fehlt",
  issuedOn: "Rechnungsdatum",
  dueOn: "Fällig am",
  notSet: "Nicht angegeben",
  lineTitle: "Beschreibung",
  // «Menge» не влезает в узкий столбец количества и ломается на две строки.
  qty: "Anz.",
  price: "Preis",
  amount: "Betrag",
  untitled: "Ohne Bezeichnung",
  subtotal: "Zwischensumme",
  vatInclusive: "inkl. VAT",
  vatExclusive: "VAT",
  netAmount: "Nettobetrag",
  discount: "Rabatt",
  vatOn: (amount) => `auf ${amount}`,
  vatOf: (percent) => `VAT · ${percent}`,
  grandTotal: "Gesamt",
  regNumber: "Reg.-Nr.",
  vatNo: "VAT-Nr.",
  addrEntrance: (value) => `Eingang ${value}`,
  addrFloor: (value) => `Etage ${value}`,
  addrApartment: (value) => `Whg. ${value}`,
  issuedShort: (date) => `Ausgestellt am ${date}`,
  dueShort: (date) => `Fällig am ${date}`,
  notesTitle: "Anmerkung",
  numberPending: "Die Nummer wird bei Ausstellung vergeben",
  paymentPurpose: (number) => `Bitte geben Sie ${number} als Verwendungszweck an.`,
  method_cash: "Bar",
  method_card: "Karte",
  method_bank: "Überweisung",
  method_other: "Sonstiges",
  footer: (number) => `Rechnung ${number}`,
  payTo: "Zahlungsdaten",
  bank: "Bank",
  payment: "Zahlung",
  status: "Status",
  paid: "Bezahlt",
  remaining: "Offen",
  paymentRow: "Zahlung",
  refundRow: "Erstattung",
  notes: "Anmerkungen",
  invoiceEyebrow: "Rechnung",
  // «Gutschrift» по-немецки — счёт, выставленный ПОКУПАТЕЛЕМ (§14 UStG);
  // продавец, отменяющий свой счёт, выписывает «Stornorechnung».
  creditNote: "STORNORECHNUNG",
  creditNoteEyebrow: "Stornorechnung",
  creditNoteFor: (number) => `Zu Rechnung ${number}`,
  creditNoteLine: (number) => (number ? `Storno der Rechnung ${number}` : "Storno der Rechnung"),
  creditNoteFooter: (number) => `Stornorechnung ${number}`,
  creditNoteTotal: "Gesamt",
  creditNoteForReceipt: (number) => `Zu Quittung ${number}`,
  creditNoteReceiptLine: (number) => (number ? `Erstattung zur Quittung ${number}` : "Erstattung zur Quittung"),
  creditNotePartialLine: (number) =>
    number ? `Teilstorno der Rechnung ${number}` : "Teilstorno der Rechnung",
  paymentsDate: "Datum",
  paymentsOperation: "Vorgang",
  paymentsEmpty: "Noch keine bestätigten Zahlungen.",
  linesTableLabel: "Rechnungspositionen",
  paymentsTableLabel: "Zahlungsverlauf",
  linesEmpty: "Noch keine Positionen.",
  status_issued: "Ausgestellt",
  status_partial: "Teilweise bezahlt",
  status_overdue: "Überfällig",
  status_paid: "Bezahlt",
  status_void: "Ungültig",
  status_cancelled: "Storniert",
};

export const ES: InvoiceDictionary = {
  locale: "es-ES",
  invoice: "FACTURA",
  draft: "Borrador",
  seller: "Emisor",
  recipient: "Destinatario",
  sellerMissing: "Emisor no indicado",
  recipientMissing: "Destinatario no indicado",
  issuedOn: "Fecha de emisión",
  dueOn: "Fecha de vencimiento",
  notSet: "No indicada",
  lineTitle: "Descripción",
  qty: "Cant.",
  price: "Precio",
  amount: "Importe",
  untitled: "Sin título",
  subtotal: "Subtotal",
  vatInclusive: "VAT incl.",
  vatExclusive: "VAT",
  netAmount: "Base imponible",
  discount: "Descuento",
  vatOn: (amount) => `sobre ${amount}`,
  vatOf: (percent) => `VAT · ${percent}`,
  grandTotal: "Total",
  regNumber: "N.º reg.",
  vatNo: "N.º VAT",
  addrEntrance: (value) => `Portal ${value}`,
  addrFloor: (value) => `Planta ${value}`,
  addrApartment: (value) => `Puerta ${value}`,
  issuedShort: (date) => `Emitida el ${date}`,
  dueShort: (date) => `Vence el ${date}`,
  notesTitle: "Observaciones",
  numberPending: "El número se asignará al emitir",
  paymentPurpose: (number) => `Indique el número ${number} como concepto del pago.`,
  method_cash: "Efectivo",
  method_card: "Tarjeta",
  method_bank: "Transferencia",
  method_other: "Otro",
  footer: (number) => `Factura ${number}`,
  payTo: "Datos de pago",
  bank: "Banco",
  payment: "Pago",
  status: "Estado",
  paid: "Pagado",
  remaining: "Pendiente",
  paymentRow: "Pago",
  refundRow: "Reembolso",
  notes: "Observaciones",
  invoiceEyebrow: "Factura",
  creditNote: "NOTA DE CRÉDITO",
  creditNoteEyebrow: "Nota de crédito",
  creditNoteFor: (number) => `Rectifica la factura ${number}`,
  creditNoteLine: (number) => (number ? `Anulación de la factura ${number}` : "Anulación de la factura"),
  creditNoteFooter: (number) => `Nota de crédito ${number}`,
  creditNoteTotal: "Total",
  creditNoteForReceipt: (number) => `Rectifica el recibo ${number}`,
  creditNoteReceiptLine: (number) => (number ? `Devolución del recibo ${number}` : "Devolución del recibo"),
  creditNotePartialLine: (number) =>
    number ? `Anulación parcial de la factura ${number}` : "Anulación parcial de la factura",
  paymentsDate: "Fecha",
  paymentsOperation: "Operación",
  paymentsEmpty: "Aún no hay pagos confirmados.",
  linesTableLabel: "Líneas de la factura",
  paymentsTableLabel: "Historial de pagos",
  linesEmpty: "Aún no hay líneas.",
  status_issued: "Emitida",
  status_partial: "Pagada parcialmente",
  status_overdue: "Vencida",
  status_paid: "Pagada",
  status_void: "Anulada",
  // «Cancelada» в бухгалтерском испанском — «погашена»; сторнированная —
  // «rectificada», как в «Rectifica la factura».
  status_cancelled: "Rectificada",
};
