// Generated by: npx supabase gen types typescript --project-id xxx > src/types/database.ts
// Run this command after applying migrations to regenerate types.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
