// STORY-062 slice 3 — shared offline-aware appointment repository wrappers.
//
// Port of apps/web/src/lib/sync/appointmentsCached.ts. Backend-neutral
// changes only (same as clientsCached.ts):
//   1. SQLite cache (`../db/cache/sql`); `readCachedAppointment` uses
//      `cacheGetOne` instead of the web `(await getCache()).get(...)`.
//   2. Web-only quota module stays out of this host-neutral wrapper. Mobile
//      preflights interactive creates in its hook and injects the policy into
//      the replayer for offline writes.
//   3. `crypto.randomUUID()` → `randomUuid()` (RN-safe).
//
// Original behaviour preserved verbatim, including the v452 UUID guard: a
// non-uuid id (legacy `apt-${ts}-rnd` from generateId("apt")) never reached
// Supabase, so update/delete on it skip the network + queue entirely (the
// optimistic cache write is the full story).
//
// Slice 5 — cache-of-DOMAIN. The cache `data` column stores the FULL
// `Appointment` domain object (the same shape `repoListAppointments`
// returns) decorated with `tenant_id` (the only bookkeeping key the domain
// shape lacks — it already carries `date` + `updated_at`). `rowToAppointment`
// returns it whole, so an online read-from-cache is byte-identical to a live
// repo read.
//
// TWO PROJECTIONS (rule 4). The queue payload is the RAW DB-column
// projection the server accepts (built by `makeServerRow` / `patchToRow`);
// the cache `data` is the full domain object (built by `makeCachedRow` /
// domain merge). dispatch relays `payload` to PostgREST; reads parse `data`.
//
// PHOTOS — the appointments row dropped its `photos` column (STORY-049);
// list/get never carry blobs (they live in appointment_photos + Storage).
// So the domain `Appointment` from the repo already has `photos: []`, and
// the cache stores that — nothing to preserve here. The photo viewer
// fetches blobs on demand (online-only), matching web + the repo contract.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "../db/database.types";
import {
  listAppointments as repoListAppointments,
  getAppointment as repoGetAppointment,
  createAppointment as repoCreateAppointment,
  updateAppointment as repoUpdateAppointment,
  deleteAppointment as repoDeleteAppointment,
} from "../db/repositories/appointments";
import type { Appointment } from "../local/appointments";
import {
  cacheRead,
  cacheUpsert,
  cacheDelete,
  cacheReplaceTenant,
  cacheGetOne,
  hasAuthoritativeTenantSnapshot,
  dequeueAll,
  type CachedAppointment,
  type CachedAppointmentData,
} from "../db/cache/sql";
// CachedAppointment (raw Row) is the queue-payload projection; CachedAppointmentData
// (full domain) is the cache-read projection. Both are used below.
import { isOnline } from "./network";
import { kickReplayer, MAX_ATTEMPTS } from "./replayer";
import {
  enqueueOpAndEmit,
  enqueueOpWithCacheUpsertAndEmit,
  enqueueOpWithCacheDeleteAndEmit,
} from "./queue-events";
import { emitRevalidated, cacheSignature } from "./revalidate-events";
import { randomUuid } from "./uuid";
import { ColdOfflineCacheMissError } from "./cache-errors";

type DbSupabase = SupabaseClient<Database>;

// v452 — UUID guard. The Supabase `appointments` table has `id` as
// uuid; sending the legacy local-storage id pattern (`apt-${ts}-rnd`,
// generated by `generateId("apt")`) makes Postgres reject the whole
// statement with «invalid input syntax for type uuid». That's how the
// PersonalEventSheet's create+delete cycle was poisoning the sync
// queue with unreplayable ops.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isUuid = (s: string): boolean => UUID_RE.test(s);

// Транспортный сбой vs семантический отказ сервера. supabase-js при
// обрыве сети отдаёт «TypeError: Failed to fetch» (Chrome) / «Load
// failed» (Safari/WebKit) / «Network request failed» (RN fetch);
// таймауты и аборты — той же природы. Всё остальное — ответ Postgres
// (RLS, constraint, 4xx), который ретраем не лечится: такие ошибки
// нельзя класть в очередь реплея (вечные ретраи), их должен увидеть
// пользователь через error-ветку мутации.
function isTransientNetworkError(err: unknown): boolean {
  // 5xx шлюза/рестарта проекта — тоже транзиент: 502/503 при живом
  // NetInfo иначе откатывал вставку вместо очереди (офлайн-first
  // регресс). PostgrestError несёт числовой status не всегда — ловим
  // и по коду, и по формулировкам шлюза.
  const withStatus = err as { status?: unknown; statusCode?: unknown };
  const httpStatus =
    typeof withStatus?.status === "number"
      ? withStatus.status
      : typeof withStatus?.statusCode === "number"
        ? withStatus.statusCode
        : 0;
  if (httpStatus >= 500) return true;
  const msg = err instanceof Error ? err.message : String(err);
  return /failed to fetch|load failed|network request failed|network error|fetch failed|timed? ?out|socket|econn|abort|bad gateway|service unavailable|gateway time|\b50[234]\b/i.test(
    msg,
  );
}

// ─── Read ─────────────────────────────────────────────────────────

export async function listAppointments(
  supabase: DbSupabase,
  tenantId: string,
): Promise<Appointment[]> {
  const cached = await safeCacheReadAppointments(tenantId);
  if (cached.length > 0) {
    void revalidateAppointments(supabase, tenantId);
    return cached.map(rowToAppointment);
  }
  // An empty row set is ambiguous: it can be a real server snapshot or a
  // device that has never synced appointments. The authoritative marker
  // written by cacheReplaceTenant disambiguates those states below.
  try {
    const fresh = await repoListAppointments(supabase, tenantId);
    await refreshCacheFromSupabase(supabase, tenantId, fresh).catch(() => {});
    return fresh;
  } catch (err) {
    // Online/server errors always reach the UI. Offline may return [] only
    // when this device previously stored an authoritative empty snapshot;
    // otherwise the calendar must render a blocked unknown state, never a
    // false «free day» that invites double-booking.
    if (isOnline()) throw err;
    const hasSnapshot = await hasAuthoritativeTenantSnapshot(
      "appointments",
      tenantId,
    ).catch(() => false);
    if (hasSnapshot) return [];
    throw new ColdOfflineCacheMissError("appointments");
  }
}

async function revalidateAppointments(
  supabase: DbSupabase,
  tenantId: string,
): Promise<void> {
  try {
    const changed = await refreshCacheFromSupabase(supabase, tenantId);
    // Emit only on a real change (loop guard — see revalidate-events).
    if (changed) emitRevalidated("appointments");
  } catch {
    // ignore — cached list already returned
  }
}

/** Refill the cache with the canonical DOMAIN list. `repoListAppointments`
 *  already maps every jsonb column into its domain shape; we only decorate
 *  each with `tenant_id` (the one bookkeeping key the domain drops — `date`
 *  + `updated_at` are already on the Appointment). Callers on the cold path
 *  pass the already-fetched list to avoid a second round-trip.
 *
 *  Slice 5 — AUTHORITATIVE + REVALIDATE-BRIDGE. `cacheReplaceTenant` prunes
 *  appointments deleted on another device; the signature diff drives the
 *  bridge emit (returns whether anything changed). */
async function refreshCacheFromSupabase(
  supabase: DbSupabase,
  tenantId: string,
  domain?: Appointment[],
): Promise<boolean> {
  // Гонка выхода в онлайн: пока в очереди висят ещё реплеящиеся
  // appointment-опы, авторитарный cacheReplaceTenant стёр бы
  // офлайн-созданную запись раньше, чем реплеер долил её на сервер
  // (запись «мигает» в календаре). Пропускаем замену — после дренажа
  // очереди onChanged/realtime ревалидирует заново, уже полным
  // снапшотом. Навсегда-упавшие опы (attempts ≥ MAX_ATTEMPTS) не
  // блокируют: их реплей не воскресит, сервер — истина.
  const pending = await dequeueAll();
  if (
    pending.some(
      (op) => op.table === "appointments" && op.attempts < MAX_ATTEMPTS,
    )
  ) {
    // Пропуск обязан сам подтолкнуть дренаж: кроме флипа сети, старта
    // приложения и следующей мутации очередь никто не разгребает — один
    // ранний транзиентный сбой иначе замораживал ревалидацию календаря
    // навсегда (guard вечно видел бы pending-оп).
    void kickReplayer({ supabase });
    return false;
  }
  const appts = domain ?? (await repoListAppointments(supabase, tenantId));
  const rows = appts.map((a) => makeCachedRow(a, tenantId));
  const before = cacheSignature(await safeCacheReadAppointments(tenantId));
  await cacheReplaceTenant("appointments", tenantId, rows);
  const after = cacheSignature(rows);
  return before !== after;
}

// Cache row → domain. The cache stores the full domain object decorated
// with tenant_id; strip it and return a clean `Appointment` (identical to
// what the repo list returns).
function rowToAppointment(r: CachedAppointmentData): Appointment {
  const { tenant_id: _t, ...appointment } = r;
  void _t;
  return appointment;
}

/** Build the DOMAIN cache row (what lands in `data`) from a canonical
 *  `Appointment`. Nested fields verbatim + the tenant_id bookkeeping key.
 *  `date` + `updated_at` are already on the domain object (the SQL layer
 *  reads them off the top level for its denorm columns). */
function makeCachedRow(
  appointment: Appointment,
  tenantId: string,
): CachedAppointmentData {
  return { ...appointment, tenant_id: tenantId };
}

// ─── Write ────────────────────────────────────────────────────────

export async function createAppointment(
  supabase: DbSupabase,
  input: Appointment,
  tenantId: string,
): Promise<Appointment> {
  const id = input.id || randomUuid();
  const nowIso = new Date().toISOString();
  // Two projections (rule 4):
  //   cachedRow — full DOMAIN object for reads.
  //   serverRow — raw DB columns for the queue payload the replayer INSERTs.
  const cachedRow = makeCachedRow(
    { ...input, id, created_at: input.created_at || nowIso, updated_at: nowIso },
    tenantId,
  );
  const serverRow = makeServerRow(input, tenantId, id, nowIso);
  const insertOp = {
    table: "appointments" as const,
    op: "insert" as const,
    row_id: id,
    payload: serverRow as unknown as Record<string, unknown>,
    expected_updated_at: null,
  };

  if (isOnline()) {
    // Optimistic UI first (standalone online — no queued op to pair with).
    await cacheUpsert("appointments", cachedRow);
    try {
      const created = await repoCreateAppointment(
        supabase,
        { ...input, id },
        tenantId,
      );
      // v452 — rebind cache from the optimistic local-id row to the
      // canonical UUID Supabase allocated. Without this, the cache
      // accumulates orphan "apt-XXX" rows alongside the real ones,
      // and a later delete on the orphan poisons the sync queue.
      if (created.id !== id) {
        try {
          await cacheDelete("appointments", id);
        } catch {
          /* ignore — cache may not have stored the optimistic row */
        }
      }
      await refetchAndCacheOne(supabase, created.id, tenantId);
      return created;
    } catch (err) {
      // Семантический отказ сервера (RLS/constraint) при живой сети —
      // НЕ в очередь (реплей гарантированно упадёт так же): откатываем
      // оптимистичную строку и пробрасываем в error-ветку мутации.
      if (isOnline() && !isTransientNetworkError(err)) {
        await cacheDelete("appointments", id).catch(() => {});
        throw err;
      }
      // Network blip — ATOMIC optimistic upsert + enqueue (risk #6).
      await enqueueOpWithCacheUpsertAndEmit(insertOp, "appointments", cachedRow);
      void kickReplayer({ supabase });
      return { ...input, id };
    }
  }

  // Offline — ATOMIC optimistic upsert + enqueue (risk #6).
  await enqueueOpWithCacheUpsertAndEmit(insertOp, "appointments", cachedRow);
  return { ...input, id };
}

export async function updateAppointment(
  supabase: DbSupabase,
  id: string,
  patch: Partial<Appointment>,
  tenantId: string,
): Promise<Appointment> {
  const existing = await readCachedAppointment(id, tenantId);
  const expectedUpdatedAt = existing?.updated_at ?? null;

  // Optimistic cache merge is DOMAIN-shaped (patch applied to the full
  // domain object); the queue payload stays the raw-column projection.
  const merged: CachedAppointmentData | null = existing
    ? {
        ...existing,
        ...patch,
        // updated_at НЕ трогаем — это серверный сентинел, он же уезжает в
        // очередь как expected_updated_at (см. clientsCached: локальный
        // штамп давал ложные «конфликты синхронизации» на каждой второй
        // офлайн-правке).
      }
    : null;

  // v452 — non-UUID ids never made it to Supabase. Skip the network +
  // queue path entirely; the optimistic cache write IS the full story, so
  // it stays a standalone upsert (there is no queued op to pair with).
  if (!isUuid(id)) {
    if (merged) await cacheUpsert("appointments", merged);
    return { ...toDomain(existing), ...patch, id } as Appointment;
  }

  const updateOp = {
    table: "appointments" as const,
    op: "update" as const,
    row_id: id,
    payload: patchToRow(patch) as Record<string, unknown>,
    expected_updated_at: expectedUpdatedAt,
  };

  if (isOnline()) {
    // Online: standalone optimistic upsert (no queued op to pair with).
    if (merged) await cacheUpsert("appointments", merged);
    try {
      const updated = await repoUpdateAppointment(
        supabase,
        id,
        patch,
        tenantId,
      );
      await refetchAndCacheOne(supabase, id, tenantId);
      return updated;
    } catch (err) {
      // RLS/constraint/business-rule failures will never succeed on replay.
      // Put the canonical cached row back and surface the error instead of
      // leaving a false optimistic edit plus a permanently poisoned queue.
      if (!isTransientNetworkError(err)) {
        if (existing) await cacheUpsert("appointments", existing).catch(() => {});
        throw err;
      }
      await enqueueUpdate(updateOp, merged);
      void kickReplayer({ supabase });
      return { ...toDomain(existing), ...patch, id } as Appointment;
    }
  }

  // Offline — ATOMIC with the optimistic row when cached (risk #6).
  await enqueueUpdate(updateOp, merged);
  return { ...toDomain(existing), ...patch, id } as Appointment;
}

/** Domain view of a cached row (drops the tenant_id bookkeeping key), or an
 *  empty base when the row wasn't cached. */
function toDomain(existing: CachedAppointmentData | null): Partial<Appointment> {
  return existing ? rowToAppointment(existing) : {};
}

/** Enqueue an update op, pairing it in one exclusive transaction with the
 *  optimistic merged row when there is one (risk #6). merged === null (row
 *  not cached) → plain emit-enqueue, matching the prior `if (existing)`. */
async function enqueueUpdate(
  op: Parameters<typeof enqueueOpAndEmit>[0],
  merged: CachedAppointmentData | null,
): Promise<void> {
  if (merged) {
    await enqueueOpWithCacheUpsertAndEmit(op, "appointments", merged);
  } else {
    await enqueueOpAndEmit(op);
  }
}

export async function deleteAppointment(
  supabase: DbSupabase,
  id: string,
  tenantId: string,
): Promise<void> {
  // v452 — non-UUID ids are local orphans (the row never made it to
  // Supabase because an earlier insert failed). Skip the network + queue
  // entirely so we don't keep re-enqueueing dead ops — a standalone
  // cacheDelete is the full story (no queued op to pair with).
  if (!isUuid(id)) {
    await cacheDelete("appointments", id);
    return;
  }

  const existing = await readCachedAppointment(id, tenantId);

  const deleteOp = {
    table: "appointments" as const,
    op: "delete" as const,
    row_id: id,
    payload: { id, tenant_id: tenantId },
    expected_updated_at: null,
  };

  if (isOnline()) {
    await cacheDelete("appointments", id); // optimistic (standalone online)
    try {
      await repoDeleteAppointment(supabase, id, tenantId);
      return;
    } catch (err) {
      if (!isTransientNetworkError(err)) {
        if (existing) await cacheUpsert("appointments", existing).catch(() => {});
        throw err;
      }
      // Fall through — ATOMIC optimistic delete + enqueue (risk #6).
      await enqueueOpWithCacheDeleteAndEmit(deleteOp, "appointments", id);
      void kickReplayer({ supabase });
      return;
    }
  }

  // Offline — ATOMIC optimistic delete + enqueue (risk #6).
  await enqueueOpWithCacheDeleteAndEmit(deleteOp, "appointments", id);
}

// ─── Helpers ──────────────────────────────────────────────────────

async function safeCacheReadAppointments(
  tenantId: string,
): Promise<CachedAppointmentData[]> {
  try {
    return await cacheRead<CachedAppointmentData>("appointments", tenantId);
  } catch {
    return [];
  }
}

async function readCachedAppointment(
  id: string,
  tenantId?: string,
): Promise<CachedAppointmentData | null> {
  try {
    // Tenant-scope the single-row read to the active tenant (minor: avoids
    // reading a row of another of the user's tenants on an id collision).
    return await cacheGetOne<CachedAppointmentData>("appointments", id, tenantId);
  } catch {
    return null;
  }
}

/** After a successful server write, refresh the cache with the CANONICAL
 *  domain row via `repoGetAppointment` (maps every jsonb column to its
 *  domain shape + carries the server's updated_at). */
async function refetchAndCacheOne(
  supabase: DbSupabase,
  id: string,
  tenantId: string,
): Promise<void> {
  const appt = await repoGetAppointment(supabase, id, tenantId).catch(() => null);
  if (!appt) return;
  await cacheUpsert("appointments", makeCachedRow(appt, tenantId));
}

function makeServerRow(
  input: Appointment,
  tenantId: string,
  id: string,
  nowIso: string,
): CachedAppointment {
  return {
    id,
    tenant_id: tenantId,
    client_id: input.client_id ?? null,
    team_id: input.team_id ?? null,
    master_id: input.master_id ?? null,
    location_id: input.location_id ?? null,
    date: input.date,
    time_start: input.time_start,
    time_end: input.time_end,
    kind: input.kind ?? "work",
    status: input.status ?? "scheduled",
    total_amount: input.total_amount ?? 0,
    custom_total: input.custom_total ?? false,
    discount_amount: input.discount_amount ?? 0,
    prepaid_amount: input.prepaid_amount ?? 0,
    comment: input.comment ?? "",
    address: input.address ?? "",
    address_note: input.address_note ?? "",
    address_lat: input.address_lat ?? null,
    address_lng: input.address_lng ?? null,
    cancel_reason: input.cancel_reason ?? null,
    source: input.source ?? null,
    is_online_booking: input.is_online_booking ?? false,
    consent_given: input.consent_given ?? true,
    color_override: input.color_override ?? null,
    city: input.city ?? null,
    reminder_enabled: input.reminder_enabled ?? false,
    reminder_offsets: (input.reminder_offsets ?? []) as unknown as CachedAppointment["reminder_offsets"],
    reminder_template: input.reminder_template ?? "",
    service_ids: (input.service_ids ?? []) as unknown as CachedAppointment["service_ids"],
    services: (input.services ?? []) as unknown as CachedAppointment["services"],
    service_price_overrides: (input.service_price_overrides ?? {}) as unknown as CachedAppointment["service_price_overrides"],
    expenses: (input.expenses ?? []) as unknown as CachedAppointment["expenses"],
    payments: (input.payments ?? []) as unknown as CachedAppointment["payments"],
    payment: (input.payment ?? null) as CachedAppointment["payment"],
    global_discount: (input.global_discount ?? null) as CachedAppointment["global_discount"],
    total_duration: input.total_duration ?? 0,
    payment_status: input.payment_status ?? "unpaid",
    payment_method: input.payment_method ?? null,
    // БЕЗ ЭТОЙ СТРОКИ офлайн-реплей молча терял бы выбранный счёт, и деньги
    // ложились бы на угаданный — ровно то, от чего мы уходим.
    payment_account_id: input.payment_account_id ?? null,
    paid_amount: input.paid_amount ?? 0,
    // STORY-055 — created_by is filled server-side by the BEFORE
    // INSERT trigger; the optimistic cache row carries null and gets
    // rewritten on refetchAndCacheOne after the real insert.
    created_by: null,
    created_at: input.created_at ?? nowIso,
    updated_at: nowIso,
    // Event-mode fields (personal calendar). All have safe defaults so
    // a non-event appointment slots in as a regular work record.
    event_all_day: input.event_all_day ?? false,
    event_notes: input.event_notes ?? "",
    event_url: input.event_url ?? "",
    event_push_enabled: input.event_push_enabled ?? false,
    event_push_offsets: (input.event_push_offsets ?? []) as unknown as CachedAppointment["event_push_offsets"],
    event_push_at: input.event_push_at ?? null,
    event_repeat: (input.event_repeat ?? { kind: "none" }) as unknown as CachedAppointment["event_repeat"],
  };
}

function patchToRow(patch: Partial<Appointment>): Partial<CachedAppointment> {
  const out: Partial<CachedAppointment> = {};
  if (patch.client_id !== undefined) out.client_id = patch.client_id;
  if (patch.team_id !== undefined) out.team_id = patch.team_id;
  if (patch.master_id !== undefined) out.master_id = patch.master_id ?? null;
  if (patch.location_id !== undefined) out.location_id = patch.location_id;
  if (patch.date !== undefined) out.date = patch.date;
  if (patch.time_start !== undefined) out.time_start = patch.time_start;
  if (patch.time_end !== undefined) out.time_end = patch.time_end;
  if (patch.kind !== undefined) out.kind = patch.kind;
  if (patch.status !== undefined) out.status = patch.status;
  if (patch.total_amount !== undefined) out.total_amount = patch.total_amount;
  if (patch.custom_total !== undefined) out.custom_total = patch.custom_total;
  if (patch.discount_amount !== undefined) out.discount_amount = patch.discount_amount;
  if (patch.prepaid_amount !== undefined) out.prepaid_amount = patch.prepaid_amount;
  if (patch.comment !== undefined) out.comment = patch.comment;
  if (patch.address !== undefined) out.address = patch.address;
  if (patch.address_note !== undefined) out.address_note = patch.address_note;
  if (patch.address_lat !== undefined) out.address_lat = patch.address_lat;
  if (patch.address_lng !== undefined) out.address_lng = patch.address_lng;
  if (patch.cancel_reason !== undefined) out.cancel_reason = patch.cancel_reason;
  if (patch.source !== undefined) out.source = patch.source;
  if (patch.is_online_booking !== undefined) out.is_online_booking = patch.is_online_booking;
  if (patch.consent_given !== undefined) out.consent_given = patch.consent_given;
  if (patch.color_override !== undefined) out.color_override = patch.color_override;
  if (patch.city !== undefined) out.city = patch.city;
  if (patch.reminder_enabled !== undefined) out.reminder_enabled = patch.reminder_enabled;
  if (patch.reminder_offsets !== undefined) out.reminder_offsets = patch.reminder_offsets as unknown as CachedAppointment["reminder_offsets"];
  if (patch.reminder_template !== undefined) out.reminder_template = patch.reminder_template;
  if (patch.service_ids !== undefined) out.service_ids = patch.service_ids as unknown as CachedAppointment["service_ids"];
  if (patch.services !== undefined) out.services = patch.services as unknown as CachedAppointment["services"];
  if (patch.service_price_overrides !== undefined) out.service_price_overrides = patch.service_price_overrides as unknown as CachedAppointment["service_price_overrides"];
  if (patch.expenses !== undefined) out.expenses = patch.expenses as unknown as CachedAppointment["expenses"];
  if (patch.payments !== undefined) out.payments = patch.payments as unknown as CachedAppointment["payments"];
  if (patch.payment !== undefined) out.payment = patch.payment as CachedAppointment["payment"];
  if (patch.global_discount !== undefined) out.global_discount = patch.global_discount as CachedAppointment["global_discount"];
  if (patch.total_duration !== undefined) out.total_duration = patch.total_duration;
  if (patch.payment_status !== undefined) out.payment_status = patch.payment_status;
  if (patch.payment_method !== undefined) out.payment_method = patch.payment_method ?? null;
  if (patch.payment_account_id !== undefined) out.payment_account_id = patch.payment_account_id ?? null;
  if (patch.paid_amount !== undefined) out.paid_amount = patch.paid_amount;
  // Event-поля личного календаря — по образцу makeServerRow. Без них
  // офлайн-правка события молча стирала event_* при реплее (payload
  // очереди не содержал колонок, а UPDATE у нас replace-семантики).
  if (patch.event_all_day !== undefined) out.event_all_day = patch.event_all_day;
  if (patch.event_notes !== undefined) out.event_notes = patch.event_notes;
  if (patch.event_url !== undefined) out.event_url = patch.event_url;
  if (patch.event_push_enabled !== undefined) out.event_push_enabled = patch.event_push_enabled;
  if (patch.event_push_offsets !== undefined) out.event_push_offsets = patch.event_push_offsets as unknown as CachedAppointment["event_push_offsets"];
  if (patch.event_push_at !== undefined) out.event_push_at = patch.event_push_at;
  if (patch.event_repeat !== undefined) out.event_repeat = patch.event_repeat as unknown as CachedAppointment["event_repeat"];
  return out;
}
